### PR TITLE
Change rkyv to serde json

### LINKED ISSUE #997: [Bug]: rkyv deserialize error on get_my_teams if there is two more team
### Expected Behavior

success

### Actual Behavior

Animation

### Steps to Reproduce

1. Create one
2. Create another one

### Other Info

```text
Uncaught (in promise) RuntimeError: unreachable
    at namui_runtime_wasm-ad0693df25ca7449.wasm.abort (namui-runtime-wasm.wasm:0x98a812)
    at namui_runtime_wasm-ad0693df25ca7449.wasm._ZN3std3sys3pal4wasi7helpers14abort_internal17ha389dc95d231a359E (namui-runtime-wasm.wasm:0x93b721)
    at namui_runtime_wasm-ad0693df25ca7449.wasm._ZN3std9panicking20rust_panic_with_hook17h041906f6553a8d16E (namui-runtime-wasm.wasm:0x94204b)
    at namui_runtime_wasm-ad0693df25ca7449.wasm._ZN3std9panicking19begin_panic_handler28_$u7b$$u7b$closure$u7d$$u7d$17hd041f8337c1f1124E (namui-runtime-wasm.wasm:0x94123a)
    at namui_runtime_wasm-ad0693df25ca7449.wasm._ZN3std3sys9backtrace26__rust_end_short_backtrace17hf1244a34678429d6E (namui-runtime-wasm.wasm:0x941174)
    at namui_runtime_wasm-ad0693df25ca7449.wasm.rust_begin_unwind (namui-runtime-wasm.wasm:0x9419ba)
    at namui_runtime_wasm-ad0693df25ca7449.wasm._ZN4core9panicking18panic_nounwind_fmt17h504ac4f688fe77daE (namui-runtime-wasm.wasm:0x952397)
    at namui_runtime_wasm-ad0693df25ca7449.wasm._ZN4core9panicking14panic_nounwind17h98dcf6719cc21302E (namui-runtime-wasm.wasm:0x9523eb)
    at namui_runtime_wasm-ad0693df25ca7449.wasm._ZN4rkyv5impls5alloc6string109_$LT$impl$u20$rkyv..Deserialize$LT$alloc..string..String$C$D$GT$$u20$for$u20$rkyv..string..ArchivedString$GT$11deserialize17h2075e3c9c7a5b292E.llvm.9566943670501111157 (namui-runtime-wasm.wasm:0x9bfd6)
    at namui_runtime_wasm-ad0693df25ca7449.wasm._ZN4rkyv5impls4core89_$LT$impl$u20$rkyv..DeserializeUnsized$LT$$u5b$U$u5d$$C$D$GT$$u20$for$u20$$u5b$T$u5d$$GT$19deserialize_unsized17had025afa784a8d28E (namui-runtime-wasm.wasm:0x9c490)

$abort	@	namui-runtime-wasm.wasm:0x98a812
$_ZN3std3sys3pal4wasi7helpers14abort_internal17ha389dc95d231a359E	@	namui-runtime-wasm.wasm:0x93b721
$_ZN3std9panicking20rust_panic_with_hook17h041906f6553a8d16E	@	namui-runtime-wasm.wasm:0x94204b
$_ZN3std9panicking19begin_panic_handler28_$u7b$$u7b$closure$u7d$$u7d$17hd041f8337c1f1124E	@	namui-runtime-wasm.wasm:0x94123a
$_ZN3std3sys9backtrace26__rust_end_short_backtrace17hf1244a34678429d6E	@	namui-runtime-wasm.wasm:0x941174
$rust_begin_unwind	@	namui-runtime-wasm.wasm:0x9419ba
$_ZN4core9panicking18panic_nounwind_fmt17h504ac4f688fe77daE	@	namui-runtime-wasm.wasm:0x952397
$_ZN4core9panicking14panic_nounwind17h98dcf6719cc21302E	@	namui-runtime-wasm.wasm:0x9523eb
$_ZN4rkyv5impls5alloc6string109_$LT$impl$u20$rkyv..Deserialize$LT$alloc..string..String$C$D$GT$$u20$for$u20$rkyv..string..ArchivedString$GT$11deserialize17h2075e3c9c7a5b292E.llvm.9566943670501111157	@	namui-runtime-wasm.wasm:0x9bfd6
$_ZN4rkyv5impls4core89_$LT$impl$u20$rkyv..DeserializeUnsized$LT$$u5b$U$u5d$$C$D$GT$$u20$for$u20$$u5b$T$u5d$$GT$19deserialize_unsized17had025afa784a8d28E	@	namui-runtime-wasm.wasm:0x9c490
$_ZN18luda_editor_client7network10server_rpc28_$u7b$$u7b$closure$u7d$$u7d$17h565025ebe5758aeaE.llvm.2352905610112850996	@	namui-runtime-wasm.wasm:0xaf777
$_ZN5tokio7runtime4task4core17Core$LT$T$C$S$GT$4poll17h5b964ed900488960E	@	namui-runtime-wasm.wasm:0xb8506
$_ZN5tokio7runtime4task7harness20Harness$LT$T$C$S$GT$10poll_inner17h55e00a1fb118ded8E	@	namui-runtime-wasm.wasm:0xe65b7
$_ZN5tokio7runtime4task7harness20Harness$LT$T$C$S$GT$4poll17hbdb2c28c9af39879E	@	namui-runtime-wasm.wasm:0xf46fc
$_ZN5tokio7runtime4task3raw4poll17h90145def3866c701E	@	namui-runtime-wasm.wasm:0xfe326
$_ZN5tokio7runtime9scheduler12multi_thread6worker7Context8run_task17ha5a67b8955c79767E	@	namui-runtime-wasm.wasm:0x4c347e
$_ZN5tokio7runtime9scheduler12multi_thread6worker7Context3run17hcb21739ed1256a8bE	@	namui-runtime-wasm.wasm:0x4c23a7
$_ZN5tokio7runtime7context6scoped15Scoped$LT$T$GT$3set17h0dd49317bf6ff559E	@	namui-runtime-wasm.wasm:0x4b7520
$_ZN3std6thread5local17LocalKey$LT$T$GT$4with17h2e34762b1fbfca73E	@	namui-runtime-wasm.wasm:0x4b98c2
$_ZN5tokio7runtime7context7runtime13enter_runtime17h1731e5ff271b97baE	@	namui-runtime-wasm.wasm:0x4c38f4
$_ZN5tokio7runtime9scheduler12multi_thread6worker3run17hd8df9edfbc9aca89E	@	namui-runtime-wasm.wasm:0x4c1a7d
$_ZN5tokio7runtime4task4core17Core$LT$T$C$S$GT$4poll17h290760023e5127d8E	@	namui-runtime-wasm.wasm:0x4afeee
$_ZN5tokio7runtime4task7harness20Harness$LT$T$C$S$GT$10poll_inner17h36328f88bbe99a5dE	@	namui-runtime-wasm.wasm:0x4c4c77
$_ZN5tokio7runtime4task7harness20Harness$LT$T$C$S$GT$4poll17hd0b0406360b8bdecE	@	namui-runtime-wasm.wasm:0x4c4aff
$_ZN5tokio7runtime4task3raw4poll17h1cabb0cacab3bc46E	@	namui-runtime-wasm.wasm:0x4bc3a6
$_ZN5tokio7runtime8blocking4pool5Inner3run17hfd872b289b47e7a0E	@	namui-runtime-wasm.wasm:0x4ad5de
$_ZN3std3sys9backtrace28__rust_begin_short_backtrace17h3ac96e64153b7f8fE	@	namui-runtime-wasm.wasm:0x4bb4ed
$_ZN4core3ops8function6FnOnce40call_once$u7b$$u7b$vtable.shim$u7d$$u7d$17h0bb4f160b4d0d940E	@	namui-runtime-wasm.wasm:0x4bbf9a
$_ZN3std3sys3pal4wasi6thread6Thread3new12thread_start17h51bb056b7cc3b163E	@	namui-runtime-wasm.wasm:0x9424f9
$__wasi_thread_start_C	@	namui-runtime-wasm.wasm:0x999941
$wasi_thread_start	@	namui-runtime-wasm.wasm:0x99ae77
self.onmessage
```

### PR DESCRIPTION
**Pull request by namse**
closes #997 

image

### CODE REVIEW

File: namui/namui-cli/src/services/rust_build_service.rs [hunk 1]
```diff
@@ -133,6 +133,10 @@ fn get_envs(build_option: &BuildOption) -> Vec<(&str, &str)> {
         envs.push(("NAMUI_CFG_WATCH_RELOAD", ""));
     }
 
+    if !build_option.release {
+        envs.push(("RUST_BACKTRACE", "1"));
+    }
+
```
Comment (bigfoodK) [inline namui/namui-cli/src/services/rust_build_service.rs:139]: This flag seems for debug, but I think it's okay to stay. What do you think?

Comment (namse) [reply namui/namui-cli/src/services/rust_build_service.rs:139]: It's intentional. only for non-release mode

**Review by bigfoodK — APPROVED** [review]
